"""Add FAQ, Review, Event, Folder, Media, QRCode, WaitingList models

Revision ID: a3e77ff39d26
Revises: a9e4b9e3de18
Create Date: 2025-03-21 17:31:52.420660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e77ff39d26'
down_revision = 'a9e4b9e3de18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_qr_codes_room_id_rooms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_qr_codes_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.drop_table('qrcodes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qrcodes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='fk_qrcodes_room_id_rooms'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_qrcodes_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('qr_codes')
    # ### end Alembic commands ###
