"""add event models

Revision ID: ad97ba584455
Revises: 1eef6216a649
Create Date: 2026-06-02 18:49:24.939580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad97ba584455'
down_revision = '1eef6216a649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_code_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=120), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('participant_type', sa.String(length=50), nullable=True),
    sa.Column('guardian_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=False),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('photos_opt_in', sa.Boolean(), nullable=True),
    sa.Column('waiver_signed', sa.Boolean(), nullable=True),
    sa.Column('agreed_terms', sa.Boolean(), nullable=True),
    sa.Column('survey_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], name=op.f('fk_event_checkins_qr_code_id_qr_codes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_checkins_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_code_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('experience_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('dams_state', sa.String(length=50), nullable=True),
    sa.Column('heart_rate_min', sa.Integer(), nullable=True),
    sa.Column('heart_rate_max', sa.Integer(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], name=op.f('fk_sessions_qr_code_id_qr_codes')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_sessions_room_id_rooms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_play_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_code_id', sa.Integer(), nullable=True),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('staff_note', sa.String(length=255), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], name=op.f('fk_sport_play_logs_qr_code_id_qr_codes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sport_play_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('starts_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'upcoming'"))

    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(true)'))

    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text("'image'"))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))
        batch_op.alter_column('approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))
        batch_op.create_foreign_key(batch_op.f('fk_medias_session_id_sessions'), 'sessions', ['session_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_guest',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(true)'))
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))
        batch_op.alter_column('is_guest',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(true)'))

    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_medias_session_id_sessions'), type_='foreignkey')
        batch_op.alter_column('approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text("'image'"))
        batch_op.drop_column('session_id')

    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(true)'))
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'upcoming'"))
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('starts_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    op.drop_table('sport_play_logs')
    op.drop_table('sessions')
    op.drop_table('event_checkins')
    # ### end Alembic commands ###
