"""Add title column to FAQ

Revision ID: e330c0a75ca1
Revises: c4b9414ac45d
Create Date: 2025-04-16 17:24:50.189715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e330c0a75ca1'
down_revision = 'c4b9414ac45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
